// DropdownButtonFormField.value is retained for compatibility with the app's
// current Flutter support range; it is replaced by initialValue on the next
// minimum-SDK upgrade.
// ignore_for_file: deprecated_member_use
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:provider/provider.dart';
import 'package:gerex/core/notifications/notification_models.dart';
import 'package:gerex/core/providers/notification_provider.dart';

class CustomNotificationScreen extends StatefulWidget {
  const CustomNotificationScreen({super.key});
  @override State<CustomNotificationScreen> createState() => _CustomNotificationScreenState();
}
class _CustomNotificationScreenState extends State<CustomNotificationScreen> {
  final _form = GlobalKey<FormState>(); final _title = TextEditingController(); final _body = TextEditingController();
  NotificationCategory _category = NotificationCategory.general; String _route = '/notifications'; String? _image;
  DateTime? _scheduledFor;
  @override void dispose() { _title.dispose(); _body.dispose(); super.dispose(); }
  Future<void> _pickImage() async { final picked = await ImagePicker().pickImage(source: ImageSource.gallery, maxWidth: 1600, imageQuality: 85); if (picked == null) return; final file = File(picked.path); final bytes = await file.length(); if (!mounted) return; final extension = picked.name.split('.').last.toLowerCase(); if (bytes > 5 * 1024 * 1024 || !{'jpg','jpeg','png','webp'}.contains(extension)) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Use a real JPG, PNG, or WebP image under 5 MB.'))); return; } setState(() => _image = picked.path); }
  Future<void> _chooseSchedule() async { final day = await showDatePicker(context: context, firstDate: DateTime.now(), lastDate: DateTime.now().add(const Duration(days: 365)), initialDate: _scheduledFor ?? DateTime.now().add(const Duration(hours: 1))); if (day == null || !mounted) return; final time = await showTimePicker(context: context, initialTime: TimeOfDay.fromDateTime(_scheduledFor ?? DateTime.now().add(const Duration(hours: 1)))); if (time != null) setState(() => _scheduledFor = DateTime(day.year, day.month, day.day, time.hour, time.minute)); }
  Future<void> _submit({required bool now}) async { if (!_form.currentState!.validate()) return; if (!now && (_scheduledFor == null || !_scheduledFor!.isAfter(DateTime.now()))) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Choose a future date and time.'))); return; } final provider = context.read<NotificationProvider>(); final template = CustomNotificationTemplate(id: DateTime.now().microsecondsSinceEpoch.toString(), title: _title.text.trim(), body: _body.text.trim(), category: _category, imagePath: _image, deepLink: _route); await provider.saveTemplate(template); final payload = NotificationPayload(id: template.id, title: template.title, body: template.body, category: template.category, imagePath: template.imagePath, deepLink: template.deepLink, scheduledTime: _scheduledFor ?? DateTime.now()); if (now) { await provider.showCustomNotification(payload); } else { await provider.scheduleNotification(payload); } if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(now ? 'Test notification sent.' : 'Notification scheduled.'))); }
  @override Widget build(BuildContext context) { final theme = Theme.of(context); return Scaffold(appBar: AppBar(title: const Text('Custom Notification')), body: ListView(padding: const EdgeInsets.all(20), children: [Text('Create a reusable local-notification template.', style: theme.textTheme.bodyMedium), const SizedBox(height: 16), Form(key: _form, child: Column(children: [TextFormField(controller: _title, maxLength: 60, decoration: const InputDecoration(labelText: 'Title'), validator: (v) => v == null || v.trim().isEmpty ? 'Enter a title' : null), TextFormField(controller: _body, maxLength: 180, maxLines: 3, decoration: const InputDecoration(labelText: 'Body'), validator: (v) => v == null || v.trim().isEmpty ? 'Enter a message' : null), DropdownButtonFormField(value: _category, items: NotificationCategory.values.map((c) => DropdownMenuItem(value: c, child: Text(c.name))).toList(), onChanged: (v) => setState(() => _category = v!), decoration: const InputDecoration(labelText: 'Category')), DropdownButtonFormField(value: _route, items: const ['/notifications','/session','/meal-planner','/activity-tracker','/sleep-tracker','/progress-photos','/coach'].map((r) => DropdownMenuItem(value: r, child: Text(r))).toList(), onChanged: (v) => setState(() => _route = v!), decoration: const InputDecoration(labelText: 'Open when tapped')), const SizedBox(height: 12), OutlinedButton.icon(onPressed: _pickImage, icon: const Icon(Icons.image_outlined), label: Text(_image == null ? 'Attach image (optional)' : 'Image attached')), OutlinedButton.icon(onPressed: _chooseSchedule, icon: const Icon(Icons.schedule), label: Text(_scheduledFor == null ? 'Choose schedule time' : _scheduledFor.toString())), const SizedBox(height: 16), Row(children: [Expanded(child: OutlinedButton(onPressed: () => _submit(now: false), child: const Text('Schedule'))), const SizedBox(width: 12), Expanded(child: ElevatedButton(onPressed: () => _submit(now: true), child: const Text('Send now')))]), ])), const SizedBox(height: 24), Text('Saved templates', style: theme.textTheme.titleMedium), ...context.watch<NotificationProvider>().templates.map((t) => ListTile(title: Text(t.title), subtitle: Text(t.body, maxLines: 1), trailing: IconButton(icon: const Icon(Icons.play_arrow), onPressed: () => context.read<NotificationProvider>().showCustomNotification(NotificationPayload(id: t.id, title: t.title, body: t.body, category: t.category, imagePath: t.imagePath, deepLink: t.deepLink, scheduledTime: DateTime.now())))))])); }
}
